### ISSUE TITLE
better favicon

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#15]
as the logo is very horizontal, we need something else as a favicon

**Comment by kohlhase** [comment]
I am sure that the HNU students will come up with something nice. I will report.

**Comment by jwknopper** [comment]
A possible alternative for a favicon, which would be reasonable easy to create is to use the O and put the m under it. This could be done as a placeholder.

**Comment by kohlhase** [comment]
we have seen some logo proposals from HNU, and we should discuss them in this context.

**Comment by davidcarlisle** [comment]
I'm not sure we should change the logo, the original OM logo was (as I recall) an M in an O but the key was chosen after extensive discussion and a vote of the society members, and it's used all over the OM documents and the new website, using a different logo just for the favicon would be a bit odd, and changing the main logo seems an unnecessary break with history.

If you want something more square you could double it up (or reflect it) or just add a coloured background or make it diagonal like 
![logo2](https://user-images.githubusercontent.com/1268738/28590211-3ee493fc-7179-11e7-801b-ed546186f9cb.png)

**Comment by davidcarlisle** [comment]
Just as a trial I switched to the diagonal one as above (the old one is favicon-old.png as well as in the git history) Actually I think the main problem with the old one was that it was almost all transparent so on dark backgrounds the text/key was hardly distinguishable, I left a central circle white here, see what you think...

**Comment by kohlhase** [comment]
a bit better, but not much :-(. Maybe we can squash it horizontally so that it becomes more square?

**Comment by davidcarlisle** [comment]
![logo10](https://user-images.githubusercontent.com/1268738/28723453-aee40b56-73ae-11e7-94f8-82944056cef2.png)

is more square?

**Comment by kohlhase** [comment]
:>, I like this.

**Comment by kohlhase** [comment]
yes, it is quite a lot more square!
