### ISSUE TITLE
make a twitter feed for OpenMath?

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#18]
we should only do this if we have someone who will tweet from time to time.

**Comment by alex-konovalov** [comment]
At the moment, https://openmath.github.io/follow/ says `Follow @openmath on Twitter` but Twitter reports that account as suspended.

**Comment by kohlhase** [comment]
I fear that this is just copy and paste from OpenDreamKit, I am not aware that OpenMath ever had a twitter account.

**Comment by kohlhase** [comment]
So if wanted to do something here, we would have to start one.

**Comment by alex-konovalov** [comment]
ok - that might be an account created by someone else and then suspended. If we want a twitter account, we may have to pick up a different twitter handle then.

**Comment by kohlhase** [comment]
maybe we should raise this issue to on the OM-SC, maybe someone knows who owns this account. Maybe Mika Sepälä did, and we should reclaim it.

**Comment by olgacaprotti** [comment]
It is indeed possible that Mika created the account.

**Comment by kohlhase** [comment]
is there a way to find out? I have no experience with twitter whatsoever (and do not want to invest). 
I think that openmath should have the control of the account, if we ever want to use it. So I guess we need a volunteer.

**Comment by olgacaprotti** [comment]
well, it looks like it belongs to a stranger to me,
![screen shot 2017-10-02 at 08 44 48](https://user-images.githubusercontent.com/377791/31066563-1a39a082-a74e-11e7-8455-47cdeb381abf.png)

does anyone know who this is?

**Comment by olgacaprotti** [comment]
Just for your info, Twitter policy:

## What if a potentially inactive account is using my registered trademark as its username or account name?
If you believe your trademark rights are being infringed and the account seems inactive, please see Twitter's trademark policy for additional information. 

## What if I have a request for a username from an account that looks inactive, but I don't have a registered trademark?
We do not generally accept requests for usernames that seem inactive. If a username you would like is being used by an account that seems inactive, you should consider selecting an available variation for your use on Twitter. In general, adding numbers, underscores, or abbreviations can help you come up with a great available username.

**Comment by kohlhase** [comment]
I do not think that we have the trademark (see https://inventively.com/search/trademarks/74464817). 
Maybe we should?

**Comment by olgacaprotti** [comment]
the process was stuck at Statement of Use, which I am not sure we can fulfil:

> To register a trademark with the U.S. Patent and Trademark Office (USPTO), you must prove that you are actively using your trademark to sell goods or sell or advertise services. In other words, you cannot register a trademark simply to tie up the rights to it. You must actually use it in commerce such as displaying it on products, packaging or other marketing materials. 


Read more at: https://www.legalzoom.com/trademarks-statement-of-use-guide/1-trademarks-statement-of-use.html

**Comment by alex-konovalov** [comment]
Updated twitter account details in 2c7b624f60120f063d1ae6276875f4adbf08e11e - it is now [@OpenMathSoc](https://twitter.com/OpenMathSoc)

**Comment by kohlhase** [comment]
and posted about it.
