### ISSUE TITLE
canonical URLs of CDs

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#24]
There is a problem in the current web site setup. 
We claim (e.g. http://www.openmath.org/cd/Official/setname1.xhtml) tha
```
Canonical URL:
http://www.openmath.org/cd/setname1.ocd
```
and that is true at the moment, but will become wrong when we move over the web site. There we only have http://www.openmath.org/cd/Official/setname1.ocd
We probably need a redirect (or generate/link the OCDs in the canonical place). 

BUT, this does not work for contributed CDs, they also claim a canonical URI, but that is not even true on the old site. What to do here?

**Comment by kohlhase** [comment]
I am assigning a lot of us to generate some discussion.

**Comment by davidcarlisle** [comment]
we need the `/cd/` version as that's used elsewhere (not least in the mathml spec) previously the official/experimental status was just flagged in the CD metadata and didn't require moving files on the website (which currently breaks some internal links eg the cdgroups pages fail to link back to the cds)

It seems github pages don't allow us to use `.httaccess` to set redirects. For html pages can use `<meta http-equiv` within the page bit we can not redirect the cd files that way.

In the previous system the web site links knew about the contrib structure so links were OK, except the canonical URL were wrong because the assumption (of the contributor) was that the contribution would be accepted so the `/cd/` link would work in the end, and before that it was a draft contribution and didn't really have a canonical url at all.

Do we need the Official and experimental directories? It would be easier to have all the files in the cd directory and then (if required) build separate index files for the official and experimental sets.

**Comment by kohlhase** [comment]
> Do we need the Official and experimental directories? It would be easier to have all the files in the cd directory and then (if required) build separate index files for the official and experimental sets.

I do not think we do, having all of them in one dir would make admin easier. 
@JamesHDavenport what do you think?

**Comment by JamesHDavenport** [comment]
I think this is one for discussion. As we discussed in Cambridge, but not really in Edinburgh,core/supported/known about would make more sense. Whether these need be different directories is a further question.


James Davenport
Fulbright CyberSecurity Scholar (at New York University)
Hebron & Medlock Professor of Information Technology, University of Bath
National Teaching Fellow 2014
OpenMath Content Dictionary Editor
Director of Studies EPSRC Doctoral Taught Course Centre for HPC
Chair, IMU Committee on Electronic Information and Communication
Vice-President and Academy Trustee, British Computer Society
________________________________

**Comment by kohlhase** [comment]
One of the reasons I like the one-directory structure state=metadata scheme much better, is that it allows us to change the status without changing the URL of the CD.

**Comment by JamesHDavenport** [comment]
In general, yes.
But ‘core’ is fixed, and supported/known about (but not on our site) is a change of URL anyway.
However, I’m not against going to one directory. Might involve looking at CDStatus, or some such. But worth thinking about, certainly.
James

**Comment by davidcarlisle** [comment]
The original reason for the separate contrib directory was that the original contrib/upload form accepted (and added) any file that was xml valid without any human peer review. the intention was that review would move them to cd as an when.

I think now if people are submitting new cds via pull requests that can be accepted or not, we should lose that and put all the cds into /cd and not add the new cd/Official and cd/experimental layers which complicate (and currently break) the internal and external linking.

So I would (to get things moving) just move all the ones in contrib to /cd  they are all already marked as experimental except plangeo1.ocd  which has CDStatus unofficial (which is invalid as far as I can see)

It would be good to retain some of the information in

http://www.openmath.org/contributed.html

which doesn't seem to be on the new site at all.

that is author of each CD

could be added as a CDComment to the OCD files I suppose, or would need to be stored elsewhere...

**Comment by kohlhase** [comment]
David, 
this would be very good. 

> It would be good to retain some of the information in
> http://www.openmath.org/contributed.html
> which doesn't seem to be on the new site at all.

I did not copy this over, since I did not want to have a central point of failure/management. 
Maybe we can put the author/submission information into comments in the ocd files?

**Comment by davidcarlisle** [comment]
> Maybe we can put the author/submission information into comments in the ocd files?

yes as I say we could put then in `CDComment` elements (or even xml `<!--` comments) but if as suggested in issue #33 we need more data such as links to source repositories etc, then allowing an optional `*.data` file with free form additional data might? work better?

**Comment by JamesHDavenport** [comment]
I'd be inclined to extend the CD language (with optional elements).
James

Sent from my iPhone

On 25 Jul 2017, at 17:42, "David Carlisle" <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe we can put the author/submission information into comments in the ocd files?

yes as I say we could put then in CDComment elements (or even xml <!-- comments) but if as suggested in issue #33<https://github.com/OpenMath/OpenMath.github.io/issues/33> we need more data such as links to source repositories etc, then allowing an optional *.data file with free form additional data might? work better?

-

**Comment by davidcarlisle** [comment]
On 25 July 2017 at 18:25, James Davenport <notifications@github.com> wrote:

> I'd be inclined to extend the CD language (with optional elements).
> James
>
>
so release an openmath 2.0 r2?

David

**Comment by JamesHDavenport** [comment]
If that’s what we decide is right, yes.

**Comment by davidcarlisle** [comment]
On 25 July 2017 at 19:18, James Davenport <notifications@github.com> wrote:

> If that’s what we decide is right, yes.
>
>
OK just asking.

In the sts files we make use of informally structured comments of the form

<CDSComment>
Date:  2003-08-06
Author: James Davenport
</CDSComment>

so we could (initially at least) do something similar to get the data in
the .ocd files as


<CDComment>
Date:   whenever
Author: someone
Source URL: https/some/external/github/repo
</CDComment>

then if [you/we/the om society] decide that  it merits a revision to add
custom elements for this it's just a simple global edit, as all the data
would
have been collected already.

David

**Comment by JamesHDavenport** [comment]
Indeed, and if we don’t want it to be machine readable, that’s probably fine.
Let’s stick with that for the time being, and see how it goes.!
James

**Comment by davidcarlisle** [comment]
and should I combine  /cd/Official,  /cd.experimental and  /contrib/cd
into  /cd  ?

**Comment by JamesHDavenport** [comment]
I think so. I’ll have to do a sortout, but that’s probably easier on the new platform anyway.
James

**Comment by davidcarlisle** [comment]
all the files have structured comments now of the form

```
<CDComment>
  Author: OpenMath Consortium
  SourceURL: https://github.com/OpenMath/CDs
</CDComment>
```

and the html presentation picks up any URL in those comments and makes them links.

The directory structure on the website is flattened by the build script with everything landing in /cd

re-arranging the source directory structure in the CDs repo to match would be possible but wouldn't add much and would require changes to the build scripts so I suggest we close this as done.

**Comment by kohlhase** [comment]
I agree. What we have seems to work (and has been cleaned up pending the PR)
