### ISSUE TITLE
put the new standard (OMSTD2R1) onto the Web Site.

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#32]
The OM Workshop approved R1 and James made the last editorial changes. So we should update OM2 in place (but keep the etitor's draft).

**Comment by davidcarlisle** [comment]
updated as https://openmath.github.io/standard/  with links to om20 r1 and editors draft and  the original om2.0 added to list of older versions 1.1 and 1,0

**Comment by kohlhase** [comment]
thanks.
