### ISSUE TITLE
Add an FAQ on constructing OMOBJs

### ISSUE THREAD

**Issue by lars-hellstrom** [OpenMath/OpenMath.github.io#34]
Sometimes when you write an OMOBJ, you come across something that you don't know how to express, even if you know the mathematics involved. One reason can of course be that we don't have symbols for that yet 😞 , but another reason can be that they're named something other than what you're looking for, and that's a case where an FAQ quickly can help you onto the right track.

Therefore I propose adding such an FAQ, e.g. as a page linked to from [https://openmath.github.io/cd/](url). Here's some content to get such an FAQ started:

### Is there an if-then-else symbol, like C's ternary `?:` operator?
Not exactly, but you can use the symbols in the `piece1` dictionary to make a piecewise function, i.e., one that is put together from several expressions, each with its own guard condition. Consider
```
<OMA><OMS cd="piece1" name="piecewise"/>
  <OMA><OMS cd="piece1" name="piece"/>
    <!-- then-expression goes here -->
    <!-- if-condition goes here -->
  </OMA>
  <OMA><OMS cd="piece1" name="otherwise"/>
    <!-- else-expression goes here -->
  </OMA>
</OMA>
```
The `if` symbol in the `prog1` dictionary is something different; it is rather about constructing an **if** statement, in a context where program fragments are objects that can be operated upon.

(The last part is conjecture on my part, but a reasonable analysis of the prog1 CD.)

The page should end with the suggestions "Was your question not found above, but you managed to figure it out anyway? Consider contributing the answer by _editing this page_." and "If you still don't know, but think it would count as a Frequently Asked Question, then _submit your question as an issue_."

**Comment by lars-hellstrom** [comment]
Here's another item.

### How do I write the imaginary unit?
There is a symbol `i` in the `nums1` content dictionary for this, so
```<OMS cd="nums1" name="i"/>```
will do the trick. Alternatively, you can use the `complex_cartesian` symbol in the `complex1` content dictionary:
```<OMA><OMS cd="complex1" name="complex_cartesian"/><OMI>0</OMI><OMI>1</OMI></OMA>```

**Comment by kohlhase** [comment]
I like the idea, and have added the page at https://openmath.github.io/cd/faq/. 
Please see/correct this.
