### ISSUE TITLE
List of all symbols has misleading title

### ISSUE THREAD

**Issue by lars-hellstrom** [OpenMath/OpenMath.github.io#35]
The page [https://openmath.github.io/symbols/](url), which is the big list of all symbols by name regardless of CD, is titled "OpenMath Content Dictionaries by name", which rather sounds like the list of all CDs [https://openmath.github.io/cdnames/](url). Indeed, the latter page _also_ says `title: OpenMath Content Dictionaries by name`.

On the old www.openmath.org, the list of all symbols page was titled "OpenMath Symbols". 

BTW, I notice that the two lists are sorted differently, with the old one bringing upper and lower case together. I think that is better, since most symbols beginning with an upper case letter are somewhat esoteric and thus not giving a representative first impression.

**Comment by kohlhase** [comment]
> On the old www.openmath.org, the list of all symbols page was titled "OpenMath Symbols".

copy/paste mistake; fixed.

**Comment by kohlhase** [comment]
> I notice that the two lists are sorted differently

I agree, I think I fixed this. Otherwise just reopen
