### ISSUE TITLE
generate statistics for CDs

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#43]
I just looked, we have about 150 CDs overall, in more than 20 CD groups. This is much more than I thought and certainly more than many of OMs critics thought prossible. We should have the statistics on the page somewhere, and keep the correct by generating them. 
Maybe also how many symbols we have. All of this should be relatively easy: generate the numbers into _data/stats.yml and then we can use them in the jekyll templates. 

cc: @JamesHDavenport

**Comment by davidcarlisle** [comment]
we already have tables of all cds and of all symbols so I think you are just asking for the row count to be added to

https://openmath.github.io/cdnames/

and

https://openmath.github.io/symbols/

These files are rebuilt on every edit.

?

**Comment by davidcarlisle** [comment]
I added some numbers to the index files listed in previous comment.

**Comment by kohlhase** [comment]
very nice, could you also generate a file `stats.yml` that has the contents
```
cdsymbols: 1532
cdcds: 135
cdgroups: 23
```
or so, and copy it into `.../openmath.github.io/data/stats.yml`, then I could just use these as variables in the general web pages (i.e. most probably on the CD overview page).

**Comment by davidcarlisle** [comment]
oh on the cdgroup count, I see we're not rebuilding the index (so if a new one were added) it wouldn't change. The old Makefile had

`$(SAXON) -it:cdg -o:$@ $(LIB)/xsl/cdgroupindex.xsl cdg="$(CDG)"`

to make `cdgroups/index.md`  but looks like I never added it to the bash script versions as used now by travis. I'll fix that up (and add a count to match the cd index) then look at piping those numbers to the yml thing.

**Comment by davidcarlisle** [comment]
done except I seem to see 19 not 23 cd groups

**Comment by kohlhase** [comment]
Oh, 23 was made up, only the format is important.

**Comment by kohlhase** [comment]
In the file I am getting we have lines
```
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
```
those should not be there :-)

**Comment by davidcarlisle** [comment]
oh that doesn't happen when I run locally, Ive seen that message in the travis logs, must be some local java config they use,, grr my simple plan of just catching the message stream into the stats file will need adjusting then, will fix

**Comment by kohlhase** [comment]
seems to work now.
