### ISSUE TITLE
fishy dir?

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#46]
I see the top-level directory `cdfiles`, is that needed? It only contains the MathML CDs? Is this for backwards compatibility?

**Comment by davidcarlisle** [comment]
it only contains a single redirect file for the mathml cdg and yes that's needed for supporting links from the mathml spec (which probably should have used the canonical one but doesn't)

> $ ls -R cdfiles/
> cdfiles/:
> cdgroups
> 
> cdfiles/cdgroups:
> mathml.cdg.html
>

**Comment by kohlhase** [comment]
OK, thanks.
