### ISSUE TITLE
Annotations in CMML view of OMOBJs in CD pages

### ISSUE THREAD

**Issue by lars-hellstrom** [OpenMath/OpenMath.github.io#48]
The OpenMath-XML view of some objects in the [scscp1](https://openmath.github.io/cd/scscp1.html) CD had very long lines, so I (uncharacteristically) took a look at the MathML view instead. That was shown as
```XML
<math xmlns="http://www.w3.org/1998/Math/MathML">
 <semantics>
  <apply><csymbol cd="scscp1">procedure_completed</csymbol><cn type="integer">26925748508234281076009</cn></apply>
  <annotation-xml cd="scscp1" encoding="call_id"><cs>a1d0c6e83f027327d8461063f4ac58a6</cs></annotation-xml>
  <annotation-xml cd="scscp1" encoding="info_runtime"><cn type="integer">72643</cn></annotation-xml>
  <annotation-xml cd="scscp1" encoding="info_memory"><cn type="integer">52876</cn></annotation-xml>
 </semantics>
</math>
```
(Still long lines, but no longer just one line with all the text on it.) 
I believe those `encoding` attributes should be `name` instead.

**Comment by kohlhase** [comment]
> I believe those encoding attributes should be name instead.

I think this is a stylesheet issue, assigning to David.

**Comment by kohlhase** [comment]
I have taken care of the long lines.

**Comment by davidcarlisle** [comment]
This would probably have been better raised as issue in Cds in any event I've fixed it there

https://github.com/OpenMath/CDs/commit/1f3aa6e7f6f7084727575f95260b427453e740f0

The update to mathml3 missed the addition of name= (originally mathml just had encoding= not name= and cd=)

**Comment by lars-hellstrom** [comment]
@davidcarlisle wrote:
> This would probably have been better raised as issue in Cds

Why? This is not an error in any CD — even if the CD could have had more reader-friendly line lengths, I didn't think it had anything technically wrong about it. The errors were clearly in the software generating a HTML rendering of the CD, and that is more part of the website, is it not?

**Comment by davidcarlisle** [comment]
the software generating the html rendering is in the CDs github repo so I needed to check it in there and remind myself not to use the simple form of issue 48 reference  so that the commit log didn't land in some unrelated issue over there with the same number.

Not a big deal but I thought it worth commenting in case more were to follow
