### ISSUE TITLE
make diff markings much more conspicuous

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OpenMath.github.io#51]
I have great difficulties even finding them in the generated html and PDF. 
It should be simple to make the colors (except the red for deleted) much less subdued. 
We do not need to hide our changes.

**Comment by davidcarlisle** [comment]
should probably have been raised on OMSTD but I added some background colour to diff marked sections

https://openmath.github.io/standard/om20-editors-draft/omstd20-diff.html#ssec_xml

also on wide screens the table of contents stays as a left sidebar

**Comment by kohlhase** [comment]
still quite elegantly subdued, but much much better. Thanks.
