### ISSUE TITLE
Dead links to java.symcomp.org  (websites for POPCORN and WUPSI) 

### ISSUE THREAD

**Issue by stub22** [OpenMath/OpenMath.github.io#64]
https://www.openmath.org/standard/scscp/
has several links to java.symcomp.org (e.g. for POPCORN and WUPSI).
However that host seems to be gone, and the current site at symcomp.org is about furniture.
Might consider replacing the dead links with direct links to the github projects here:
https://github.com/symcomp

**Comment by alex-konovalov** [comment]
Thank you for reporting this, @stub22!

CC @no-dashes
