### ISSUE TITLE
Github pages at http://openmath.github.io/om-rdf

### ISSUE THREAD

**Issue by kenwenzel** [OpenMath/OpenMath.github.io#68]
I like to publish a subpage at http://openmath.github.io/om-rdf which is contained within the branch `gh-pages` of the `om-rdf` repo.
Unfortunately, it cannot be accessed because `openmath.github.io` redirects to `openmath.org`.

Do you have any suggestions?

**Comment by davidcarlisle** [comment]
I'm not sure I undersand the issue, why is the redirect a problem?  If you push a document to the master branch it should appear at openmath.org, gh-pages branches are not used.

**Comment by davidcarlisle** [comment]
I works for me without the slash, in fact the link in your original comment works and shows the document (which is why I was confused:-) We don't have a lot of control over the github.io  redirects so can we close this?

If I use `wget` you see the redirect from `om-rdf` to `om-rdf/` working with a `301 Moved Permanently` response code:

```
$ wget  https://openmath.org/om-rdf
--2022-05-13 18:53:42--  https://openmath.org/om-rdf
Resolving openmath.org (openmath.org)... 185.199.110.153, 185.199.111.153, 185.199.108.153, ...
Connecting to openmath.org (openmath.org)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://openmath.org/om-rdf/ [following]
--2022-05-13 18:53:42--  https://openmath.org/om-rdf/
Reusing existing connection to openmath.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 70388 (69K) [text/html]
Saving to: ‘om-rdf’
```

**Comment by kenwenzel** [comment]
Yes, you are right. The original link is working. Maybe I was a bit too fast when testing it. Thank you for your support!
